### ISSUE TITLE
Request: Add fields like postcode and latlng

### ISSUE THREAD

**Issue by fakiolinho** [hnassr/nova-places#1]
Great work @hnassr !!! Do you intent to add some extra fields such as postcode and latlng?

Thanks again

**Comment by hnassr** [comment]
Hey @fakiolinho I just tagged a new [release (v1.0.3)](https://github.com/hnassr/nova-places/releases/tag/v1.0.3) with latlng and postcode fields


feel free to test it

**Comment by fakiolinho** [comment]
Awesome!!! You rock @hnassr  🙌
